### ISSUE TITLE
Obtain N-BNN access

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#4]
German foodcoops use articles from [N-BNN](http://n-bnn.de/). We'll need FTP credentials to allow  [sharedlists](https://github.com/foodcoops/sharedlists) to synchronize it for the [shared database feature](https://github.com/foodcoops/foodsoft/wiki/Shared-database). Maybe @bennibu would be able to refer us, or we can ask a foodcoop that orders from one of their suppliers to bring us in contact.

Configuring this depends on #3.

**Comment by bennibu** [comment]
@wvengen Sorry, I can't provide these credentials. There were given to me as a member of foodcoop a long time ago. But I guess, if you ask one of the involved coops this would not be a problem.

**Comment by wvengen** [comment]
Thanks, Benni, for your quick response. Should be no problem indeed.

**Comment by robwa** [comment]
Are this general BNN credentials? Is there a centralized database? I could try to obtain credentials for the [Terra](http://terra-natur.com/service/) database.

**Comment by wvengen** [comment]
Good question. I think Terra is the more important. There may be two versions of the article lists, as seen below.

---

For information, these are all the shared suppliers on the old foodcoops.net infrastructure:

Name | Adresse | Notiz | Liefertage
-- | -- | -- | --
Terra Naturkost Handels KG | Gradestraße 92, 12347 Berlin |   | Di, Do (?) bis 12Uhr
Ökotopia [nicht aktuell] | Gneisenaustraße 2a, 10961 Berlin | Ökotopia  vertreibt eine große Auswahl an leckerem Tee und Kaffee. 1980 wurde das  Kollektiv aus einer Forschungsgruppe der FU-Berlin gegründet. Ökotopia  ist eine Not-for-profit-Organisation, bei der die Überschüsse direkt in  die Refinanzierung fließen.
Midgard (FC Hessenhagen) | Holzstraße 7, 13359 Berlin | Großhandel  in Berlin. Trocken- und Frischwaren. Ein großer Teil sind Demeter  Produkte. Die Artikel kommen 'soweit möglich' aus der Region  Berlin/Brandenburg
Märkisches Landbrot [nicht aktuell] | Bergiusstraße 36, 12057 Berlin | Märkisches  Landbrot ist eine mittelständische ökologische Bäckerei mit Sitz im  Gewerbegebiet Berlin - Neukölln. Das Sortiment ist riesig und es können  darüber hinaus auch Backwaren von anderen Bäckereien (Tillmann etc.)  bestellt werden. | Mo-Sa
Borkenstein | Hiddenseer Strasse 11 |   | 
Grell Naturkost | Feldstraße 3b, 24568 Kaltenkirchen |   | 
Filderwerkstatt | 73265 Dettingen |   | 
Naturkost Nord | Am Bauhof 2, 21218 Seevetal |   | 
Terra (nur gewerbliche Kunden!) | Gradestraße 92, 12347 Berlin | Bitte beachtet, diese Preislisten sind nur für gewerbliche Kunden von Terra gemacht. Also keine normalen Foodcoops.

**Comment by wvengen** [comment]
As a sidenote, we may want to check with Hessenhagen (who is also migrating) if Midgard is desired in the shared database. If yes, we can ask if they can connect us with them for synchronizing the article list.

**Comment by robwa** [comment]
I would like to ask coops, which suppliers are needed. I wait for #11 to have communication infrastructure.

**Comment by robwa** [comment]
Terra won't give us a pseudo account for read access. But they told us, that one FC may use their login. I can provide one.

**Comment by wvengen** [comment]
Thanks for checking, sounds good. When sharedlists is running, maybe you can setup the supplier.

**Comment by robwa** [comment]
I guess, I can setup Terra now. Do I need access to the server or does sharedlists have a web interface (I can't remember, sorry)?

**Comment by paroga** [comment]
Shouldn't we also transfer the current database of app.foodcoops.at first to ensure that the mapping between sharedlists and foodsoft stays correct?

The interface can be found at: https://app.foodcoops.net.foodcoops.info/sharedlists/

**Comment by wvengen** [comment]
That is not necessary, foodsoft-sharedlists mapping works with supplier number, not with internal ids (iirc).

**Comment by robwa** [comment]
Added Terra to the db. Hopefully working.

Can we close this?

**Comment by wvengen** [comment]
Let's wait until we see the articles are synchronized correctly.
(Note that for editing the supplier you need to enter the password - bug https://github.com/foodcoops/sharedlists/issues/9)

**Comment by robwa** [comment]
Where/ How do I find synchronization logs?

**Comment by wvengen** [comment]
This is likely to be part of the sharedlists cron output. If it works, you'll see articles.
It is also possible to run a rake task manually, I guess (would need to look it up).

**Comment by robwa** [comment]
Disclaimer: I have never used docker and have no idea how it works.

What I found out:
* By specification in the sharedlists Dockerfile a crontab is generated (`bundle exec whenever >crontab`)
* This crontab seems to be used by the cron process defined in Procfile
* The following task is run: `RAILS_ENV=production bundle exec rake sync_bnn_files`
* If I run this command manually, it says at the end `Sync bnn files for  Terra Naturkost Handels KG...`
* No errors, no articles, it takes almost no time.

What is the preferred way to debug things like this with docker?

**Comment by wvengen** [comment]
The rake tasks calls [#sync_bnn_files](https://github.com/foodcoops/sharedlists/blob/master/app/models/supplier.rb#L18) for each supplier, which first synchronizes from ftp in [FtpSync](https://github.com/foodcoops/sharedlists/blob/master/lib/ftp_sync.rb#L9).
I have never used this before (never able to test it). It would be a good idea to check file synchronization first, and see if the right files would be downloaded.

**Comment by robwa** [comment]
* I didn't find any cron logs so far
* manual execution showed an error
* one has to delete files in `supplier_assets/bnn_files/?/` for repeated testing
* Fixed things in https://github.com/foodcoops/sharedlists/pull/10
* Can someone merge this and deploy?
* Afterwards we can check via the update timestamp on the suppliers page if it worked.
* If someone finds cron logs, we can even check them.

**Comment by wvengen** [comment]
@robwa cron logs are docker container stdout log (else attach to container with exec to see files maybe)

**Comment by wvengen** [comment]
It looks like this is working now!
Do cron-based updates work as well? (Last update now is from 30 Nov.)

**Comment by robwa** [comment]
No, they don't seem to work. Terra files should update at least weekly. Where can I find documentation on who calls cron when and why ...?

**Comment by wvengen** [comment]
Cron is run from docker (see [`sharedlists_cron` in docker-compose.yml](https://github.com/foodcoops/foodcoops.net/blob/master/docker-compose.yml#L83)), which logs to stdout, so it appears in the docker logs (see [`docker-compose logs`](https://docs.docker.com/compose/reference/logs/)).

If the rake task works, cron _should_ work as well. Otherwise we have a bug there.

**Comment by robwa** [comment]
Thank you!

What I found out:
* cron is running
* the bnn files are synchronized (file timestamps are ok)
* the error fixed in https://github.com/foodcoops/sharedlists/pull/10 is still present on the host

As far as I understand, deployment happens daily via script. Do we need to tag a release or something like that?

**Comment by wvengen** [comment]
Good you found the cause. There was a Debian repository connection error during the Docker build, that seems to have been resolved. I've triggered a new build, which should be auto-deployed tomorrow.

**Comment by robwa** [comment]
We still get (2017-12-15T16:14:03Z)

```
NoMethodError: undefined method `set_encoding' for "/usr/src/app/supplier_assets/bnn_files/3/./PLF.BNN":String
/usr/src/app/lib/article_import/bnn.rb:48:in `parse'
...
```

which is [no longer there](https://github.com/foodcoops/sharedlists/blob/master/lib/article_import/bnn.rb#L48).

The fix doesn't get deployed. Any ideas?

**Comment by wvengen** [comment]
Maybe the deployment cronjob doesn't work or isn't step, perhaps. Did you try [depoying manually](https://github.com/foodcoops/foodcoops.net#deploying)? It looks like the last sharedlists commit is built [on Docker](https://hub.docker.com/r/foodcoops/sharedlists/builds/).

**Comment by robwa** [comment]
Took quite some time, but now it seems to work. The timestamp was updated yesterday by cron.

Thank you for your support, @wvengen!
